

cd MyDCUtils
del *.o
del *.s
del *.rc
del *.res
del dcutils.dll
del dcutils.lib
del dcutils.dec
del *.bak
cd..

cd MyDCMoodll
del *.o
del *.s
del *.rc
del *.res
del moodll.lib
del moodll.dll
del moodll.dec
del *.bak
cd..

cd MyDCZip
del *.o
del *.s
del *.rc
del *.res
del MyDCZip.lib
del MyDCZip.dll
del MyDCZip.dec
del *.bak
cd..

cd MyDCPluginTemplate
del *.o
del *.s
del *.rc
del *.res
del dcptemplate.lib
del dcptemplate.dll
del dcptemplate.dec
del *.bak
cd..

cd MyDCPubCmdBots
del *.o
del *.s
del *.rc
del *.res
del PubCmdBots.lib
del PubCmdBots.dll
del PubCmdBots.dec
del *.bak
cd ..

del dcutils.dll
del moo.dll
del MyDC.exe
del _MyDC.exe
del MyDC.o
del MyDC.s
del MyDC.res
del *.bak








